// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbmooyhuyynlamajkicz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibW9veWh1eXlubGFtYWpraWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTYxNTQsImV4cCI6MjA2ODMzMjE1NH0.XHzcj05aflmIBEbhlutucv_eyoYzAASNo-o38alnPlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});